const MdActionTypes = {
  FETCH_MDCOLLECTIONS_START: 'FETCH_MDCOLLECTIONS_START',
  FETCH_MDCOLLECTIONS_SUCCESS: 'FETCH_MDCOLLECTIONS_SUCCESS',
  FETCH_MDCOLLECTIONS_FAILURE: 'FETCH_MDCOLLECTIONS_FAILURE'
};

export default MdActionTypes;
